spring:
  application:
    name: task-test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      enabled: false  # Enable H2 web console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      platform: h2
      mode: embedded
logging:
  level:
    root: INFO
    org.springframework.web: INFO
  file:
    name: logs/spring-boot-app-test.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - [%thread] %-5level %logger{36} - %msg%n"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
