INSERT INTO COURSES(type, NAME)
values (0, 'Math'),
       (0, 'English'),
       (0, 'Biology'),
       (0, 'Physics'),
       (0, 'Literature'),
       (1, 'Art'),
       (1, 'Physical Education'),
       (1, 'Music'),
       (1, 'History'),
       (1, 'Psycology'),
       (1, 'Handcraft'),
       (1, 'Chemistry');

INSERT INTO GROUPS (GROUP_NAME)
VALUES ('1a'),
       ('1b'),
       ('1c'),
       ('1d'),
       ('1e');

INSERT INTO users (name, age, user_type)
VALUES ('Dr. Constance White', '18', 'TEACHER'),
       ('Charles Osinski', '7', 'STUDENT'),
       ('Elsa Leffler', '22', 'STUDENT'),
       ('Dustin Medhurst', '21', 'STUDENT'),
       ('Mr. Shelly Marquardt', '23', 'STUDENT'),
       ('Kathy Treutel', '13', 'STUDENT'),
       ('Leah McDermott', '23', 'TEACHER'),
       ('Gwendolyn Swift', '18', 'TEACHER'),
       ('Essie Lehner', '12', 'STUDENT'),
       ('Tami Cartwright', '19', 'TEACHER'),
       ('Kelly Bogisich', '16', 'TEACHER'),
       ('Todd Mayer', '20', 'STUDENT'),
       ('Patsy Marquardt', '20', 'STUDENT'),
       ('Barry O''Reilly', '21', 'TEACHER'),
       ('Milton Rosenbaum', '9', 'STUDENT'),
       ('Ms. Gilbert Nolan', '22', 'TEACHER'),
       ('Clay Tromp', '8', 'STUDENT'),
       ('Leo Funk', '10', 'TEACHER'),
       ('Willie Bradtke', '8', 'STUDENT'),
       ('Joan McKenzie', '23', 'TEACHER'),
       ('Armando Huel', '21', 'STUDENT'),
       ('Jason Weimann', '23', 'TEACHER'),
       ('Mrs. Thomas Hoppe', '10', 'STUDENT'),
       ('Horace Walsh I', '13', 'TEACHER'),
       ('Annette Pouros', '17', 'STUDENT'),
       ('Noah Senger', '21', 'TEACHER'),
       ('Hector Greenfelder', '15', 'STUDENT'),
       ('Rochelle Vandervort', '21', 'TEACHER'),
       ('Isabel Lindgren', '13', 'TEACHER'),
       ('Raul Larkin', '11', 'TEACHER'),
       ('Dewey Zulauf', '12', 'STUDENT'),
       ('Allan Towne', '13', 'STUDENT'),
       ('Francis O''Connell', '18', 'STUDENT'),
       ('Ada Runolfsdottir', '22', 'STUDENT'),
       ('Adrian Yost', '7', 'STUDENT'),
       ('Florence Zboncak', '12', 'STUDENT'),
       ('Kristine Rippin', '25', 'TEACHER'),
       ('Emilio Beahan', '11', 'STUDENT'),
       ('Doris Schinner', '21', 'STUDENT'),
       ('Wanda Kohler', '17', 'TEACHER'),
       ('Mona Botsford', '19', 'STUDENT'),
       ('Christina Labadie', '23', 'STUDENT'),
       ('Gladys Hamill', '20', 'TEACHER'),
       ('Yvette Gibson', '8', 'STUDENT'),
       ('Leah Kemmer', '12', 'TEACHER'),
       ('Conrad Okuneva', '11', 'TEACHER'),
       ('Rodolfo Dickinson', '22', 'TEACHER'),
       ('Carole Schuster', '20', 'STUDENT'),
       ('Adrienne Reilly I', '10', 'TEACHER'),
       ('Miss Maryann Medhurst', '20', 'STUDENT'),
       ('Pat Daugherty', '14', 'TEACHER'),
       ('Guadalupe Cassin', '13', 'TEACHER'),
       ('Tonya Bogisich', '19', 'TEACHER'),
       ('Wendell Stamm', '15', 'STUDENT'),
       ('Herman Graham', '9', 'STUDENT'),
       ('Adam Padberg', '11', 'TEACHER'),
       ('Jacquelyn Dach', '25', 'TEACHER'),
       ('Mr. Jeffrey O''Conner', '24', 'TEACHER'),
       ('Dennis Hartmann', '25', 'TEACHER'),
       ('Erica Hammes I', '20', 'STUDENT'),
       ('Joy Ziemann', '11', 'STUDENT'),
       ('Elijah Kerluke', '16', 'STUDENT'),
       ('Heather Renner', '20', 'STUDENT'),
       ('Andre Lesch', '12', 'TEACHER'),
       ('Chad Legros', '13', 'STUDENT'),
       ('Ms. Gary Ruecker', '21', 'TEACHER'),
       ('Ms. Sonya Towne', '25', 'TEACHER'),
       ('Jackie Marks', '16', 'STUDENT'),
       ('Ms. Damon Barton', '8', 'TEACHER'),
       ('Floyd Lockman', '7', 'STUDENT'),
       ('Jack Klein', '11', 'STUDENT'),
       ('Jessie Heathcote', '17', 'TEACHER'),
       ('Miss Geraldine Goodwin', '24', 'STUDENT'),
       ('Perry Torphy', '22', 'STUDENT'),
       ('Cathy Bode', '16', 'STUDENT'),
       ('Clark Nader', '10', 'TEACHER'),
       ('Belinda Reinger', '14', 'TEACHER'),
       ('Andre Lesch', '21', 'STUDENT'),
       ('Miss Wesley Labadie III', '23', 'STUDENT'),
       ('Jeannie Luettgen', '17', 'TEACHER'),
       ('Mrs. Priscilla Walter', '7', 'TEACHER'),
       ('Raymond Stehr', '19', 'STUDENT'),
       ('Constance Mraz', '12', 'TEACHER'),
       ('Irma McDermott', '21', 'STUDENT'),
       ('Dewey Lueilwitz', '21', 'TEACHER'),
       ('Jaime Kiehn', '23', 'TEACHER'),
       ('Alice Quigley II', '13', 'STUDENT'),
       ('Henry Pouros', '11', 'TEACHER'),
       ('Edna Nader', '20', 'STUDENT'),
       ('Marco Nitzsche', '19', 'TEACHER'),
       ('Ebony Klocko', '10', 'TEACHER'),
       ('Franklin Franey', '9', 'TEACHER'),
       ('Terry Zboncak', '7', 'STUDENT'),
       ('Horace Langworth', '7', 'TEACHER'),
       ('Sean Collier MD', '8', 'TEACHER'),
       ('Carlos Moen', '25', 'STUDENT'),
       ('Beverly Konopelski', '19', 'TEACHER'),
       ('Ms. Cecil Ritchie V', '14', 'STUDENT'),
       ('Dr. Anita Yundt', '14', 'STUDENT'),
       ('Dr. Kendra Farrell', '20', 'TEACHER');
