DROP TABLE if EXISTS courses CASCADE;
DROP TABLE if EXISTS groups CASCADE;
DROP TABLE if EXISTS user_course CASCADE;
DROP TABLE if EXISTS user_group CASCADE;
DROP TABLE if EXISTS users CASCADE;
CREATE TABLE users
(
    user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(255)                              NOT NULL,
    age       SMALLINT                                  NOT NULL,
    user_type TINYINT CHECK (user_type BETWEEN 0 AND 1) NOT NULL,
    PRIMARY KEY (user_id)
);
CREATE TABLE courses
(
    course_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type      TINYINT CHECK (type BETWEEN 0 AND 1) NOT NULL,
    name      VARCHAR(255)                         NOT NULL UNIQUE,
    PRIMARY KEY (course_id)
);
CREATE TABLE groups
(
    group_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    group_name VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (group_id)
);
CREATE TABLE user_course
(
    user_id   bigint not null,
    course_id bigint not null,
    CONSTRAINT user_course_uk UNIQUE (user_id, course_id),
    CONSTRAINT user_2_course_USERS_USER_ID_fk FOREIGN KEY (user_id) REFERENCES USERS,
    CONSTRAINT FK36vk1gf5akhk4ta4sdehlbsu8 FOREIGN KEY (course_id) REFERENCES courses
);
CREATE TABLE user_group
(
    user_id  bigint not null,
    group_id bigint not null,
    CONSTRAINT USER_GROUP_pk UNIQUE (GROUP_ID, USER_ID),
    CONSTRAINT FKbegtgnl3oq004958pisko4fu4 FOREIGN KEY (group_id) REFERENCES groups,
    CONSTRAINT FK7k9ade3lqbo483u9vuryxmm34 FOREIGN KEY (user_id) REFERENCES users
);
