DROP TABLE if EXISTS courses cascade;
DROP TABLE if EXISTS groups cascade;
DROP TABLE if EXISTS user_course cascade;
DROP TABLE if EXISTS user_group cascade;
DROP TABLE if EXISTS users cascade;
CREATE TABle users (age smallint not null, user_id bigint generated by default as identity, user_type varchar(31) not null, name varchar(255) not null, primary key (user_id));
CREATE TABle courses (type tinyint check (type between 0 and 1), course_id bigint generated by default as identity, name varchar(255) not null unique, primary key (course_id));
CREATE TABle groups (group_id bigint generated by default as identity, group_name varchar(255) not null unique, primary key (group_id));
CREATE TABle user_course (course_id bigint not null, user_id bigint not null, constraint user_course_uk unique (user_id, course_id), constraint user_2_course_USERS_USER_ID_fk foreign key (user_id) references USERS , constraint FK36vk1gf5akhk4ta4sdehlbsu8 foreign key (course_id) references courses );
CREATE TABle user_group (group_id bigint not null, user_id bigint not null, constraint USER_GROUP_pk
    unique (GROUP_ID, USER_ID),constraint FKbegtgnl3oq004958pisko4fu4 foreign key (group_id) references groups,constraint FK7k9ade3lqbo483u9vuryxmm34 foreign key (user_id) references users);
